apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarm-db
  template:
    metadata:
      labels:
        app: alarm-db
    spec:
      containers:
        - name: alarm-db
          image: mariadb
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: alarm-config
                  key: ALARM_DB_USER
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: alarm-config
                  key: ALARM_DB_NAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alarm-db-passwd-secret
                  key: ALARM_DB_USER_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alarm-db-passwd-secret
                  key: ALARM_DB_ROOT_PASSWORD
          volumeMounts:
            - name: alarm-db-data
              mountPath: /var/lib/mysql
              subPath: db
      volumes:
        - name: alarm-db-data
          persistentVolumeClaim:
            claimName: alarm-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: alarm-db-srv
spec:
  type: ClusterIP
  selector:
    app: alarm-db
  ports:
    - name: alarm-db
      protocol: TCP
      port: 3306
      targetPort: 3306
