apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
        system: panda
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: check-db-ready
          image: postgres:alpine
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h nats-db-srv -p 5432; do echo waiting for database; sleep 2; done;",
            ]
      containers:
        - name: nats
          image: nats-streaming
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "384Mi"
              cpu: "100m"
          env:
            - name: NATS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: NATS_DB_USER
            - name: NATS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: NATS_DB_NAME
            - name: NATS_DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: nats-db-passwd-secret
                  key: NATS_DB_PASSWD
          args:
            [
              "-st",
              "SQL",
              "--sql_driver",
              "postgres",
              "--sql_source",
              "user=$(NATS_DB_USER) password=$(NATS_DB_PASSWD) host=nats-db-srv port=5432 dbname=$(NATS_DB_NAME) sslmode=disable",
              "-p",
              "4222",
              "-m",
              "8222",
              "-hbi",
              "5s",
              "-hbt",
              "5s",
              "-hbf",
              "2",
              "-SD",
              "-cid",
              "acss",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
